// Module included in the following assemblies:
//
// * installing/installing_bare_metal/installing-bare-metal.adoc
// * installing/installing_restricted_networks/installing-restricted-networks-bare-metal.adoc
// * installing/installing_ibm_z/installing-ibm-z.adoc

[id="installation-user-infra-machines-iso_{context}"]
= Creating {op-system-first} machines

Before you install a cluster on z/VM guest virtual machines,
you must install Red Hat Enterprise Linux CoreOS on those virtual machines.

.Prerequisites
ifeval::["{context}" == "installing-ibm-z"]
* An FTP server running on your provisioning machine that is accessible to the machines you create.
endif::[]

* Have access to an FTP server that you can access from your computer and that
the machines that you create can access.
* Parameter files for your machines

.Procedure
ifeval::["{context}" == "installing-ibm-z"]
. Log in to Linux on your provisioning machine.
. Download the Red Hat Enterprise Linux CoreOS installation files from the link:https://mirror.openshift.com/pub/openshift-v4/s390x/dependencies/rhcos/4.2/latest/[{op-system} image mirror].
endif::[]

. Download the Red Hat Enterprise Linux CoreOS installation files from https://mirror.openshift.com/pub/openshift-v4/s390x/dependencies/rhcos/4.2/latest/
+
[IMPORTANT]
====
The {op-system} images might not change with every release of {product-title}.
You must download images with the highest version that is less than or equal
to the {product-title} version that you install. Use the image versions
that match your {product-title} version if they are available.
====
+
Download the following files:

** The initramfs: `rhcos-<version>-installer-initramfs.img`
** The kernel: `rhcos-<version>-installer-kernel`
** The operating system image for the install medium you want to use, `rhcos-<version>-
dasd.raw.gz` for DASD.

. Create a parameter file, or use one created by the OpenShift installer. The following parameters need special attention:
** rd.dasd=
is the DASD for the different z/VM virtual machines.
** ip=
** is the IP address for the different z/VM virtual machines.
** coreos.inst.ignition_url=
gets the specific ignition file according to the machine role. The bootstrap machine ignition file is
called bootstrap-0, the master ignition files are numbered 0 through 2, the worker ignition files from 0
upwards. All other parameters can stay as they are.

. Transfer the initramfs, kernel, and parameter file  to the virtual reader of your bootstrap machine
+
[TIP]
====
You can use either CMS or, if you use Linux, the vmur cmd.
====
+
. IPL the bootstrap machine from the reader, i.e. from the default "c" device

. Continue to create the machines for your cluster.
+
[IMPORTANT]
====
You must create the bootstrap and control plane machines at this time. Because
some pods are deployed on compute machines by default, also create at least two
compute machines before you install the cluster.
====
endif::[]
