// Module included in the following assemblies:
//
// * machine_management/applying-autoscaling.adoc

[id="machine-autoscaler-about_{context}"]
= About the MachineAutoscaler

The MachineAutoscaler adjusts the number of Machines in the MachineSets that you
deploy in an {product-title} cluster. You can scale both the default `worker`
MachineSet and any other MachineSets that you create. The MachineAutoscaler
makes more Machines when the cluster runs out of resources to support more
deployments. The MachineAutoscaler also reconciles any changes that you make to
the MachineSets, such as changing the minimum or maximum number of instances.

[IMPORTANT]
====
You must deploy a MachineAutoscaler for the ClusterAutoscaler to scale your
machines. The ClusterAutoscaler uses the annotations on MachineSets that the
MachineAutoscaler sets to determine the resources that it can scale. If you
define a ClusterAutoscaler without also defining MachineAutoscalers, the
ClusterAutoscaler will never modify your cluster.
====
