repository: ocp-tests
variants:
 - name: openshift-container-platform
   attributes:
    - _attributes/ocp-attributes.adoc
   build: true
   files:
     included:
       - openshift_images/**/*.adoc
       - images/*.png
       - images/*.svg
       - modules/**/*.adoc


