repository: ocp-tests
variants:
 - name: openshift-container-platform
   attributes:
    - _attributes/ocp-attributes.adoc
   build: true
   files:
     included:
       - openshift_images/**/*.adoc
       - images/*.png
       - images/*.svg
       - modules/**/*.adoc
     excluded:
       - _unused_topics
       - _package
       - _stylesheets
       - scripts
       - whats_new
       - getting_started
       - cloud_infrastructure_access
       - administering_a_cluster
       - _images
       - _javascript
       - _preview
       - _snippets
       - _templates


